version: "3.8"
services:
  library-cache-server:
    build:
      dockerfile: Dockerfile
      context: ./
    image: library-cache-server:v0.0.2
    container_name: library-cache-server
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    command:
      - "java"
      - "-Dserver.port=80"
      - "-jar"
      - "app.jar"
#    ports:
#      - "81:8080"
    volumes:
      - "/home/data/docker/library-cache/cache/:/home/cache/"
    networks:
      np-nw:
        ipv4_address: 192.168.2.200
networks:
  np-nw:
    external:
      name: "np-network"
