version: "3.8"
services:
  library-cache-server:
    build:
      dockerfile: Dockerfile
      context: ./
    image: trevet/library-cache-server:0.0.2
    container_name: library-cache-server
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    command:
      - "java"
      - "-Dserver.port=80"
      - "-jar"
      - "app.jar"
    ports:
      - "81:80"
    volumes:
      - "/home/data/docker/library-cache/cache/:/home/cache/"